# ref: https://hub.docker.com/_/golang/
FROM golang:1.7

WORKDIR /go/src/app

RUN go-wrapper download github.com/labstack/echo/... \
                        github.com/go-sql-driver/mysql \
                        github.com/gocraft/dbr
